### ISSUE TITLE
Not receiving the mail to activate the course

### ISSUE THREAD

**Issue by Archiesachin** [GSSoC24/Postman-Challenge#1102]
I registered on the link given but i am getting the mail to activate the course. Its been 1/2 an hour since i registered. Also tried with a different email id but still not receiving the mail.

**Comment by MastanSayyad** [comment]
@Archiesachin Check spam

**Comment by Archiesachin** [comment]
> @Archiesachin Check spam

nothing received yet

**Comment by MastanSayyad** [comment]
> > @Archiesachin Check spam
> 
> nothing received yet

Try login to the postman workspace and see if you can move further to complete the course, if yes then do it, if no then they will ask you to verify the email again!
