### ISSUE TITLE
Postman API Fundamentals Student Expert certificate!

### ISSUE THREAD

**Issue by Shaanif600** [GSSoC24/Postman-Challenge#2345]
i hope this message finds you well. I am writing to formally request access to the GitHub repository for postman-challenge as a project administrator

**Comment by 345captain** [comment]
add my name #877 
![Uploading Postman - Postman API Fundamentals Student Expert - 2024-09-29 (1).png…]()

**Comment by AKSHITHA-CHILUKA** [comment]
@Shaanif600  Sorry You cannot be a project administrator

**Comment by Shaanif600** [comment]
> @Shaanif600  Sorry You cannot be a project administrator 
My account was hacked by someone sorry for that request
