### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by aditiverma-21** [GSSoC24/Postman-Challenge#2353]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

**Comment by dev15Aditya** [comment]
Hey @aditiverma-21 
I would like to work on it.

**Comment by aditiverma-21** [comment]
@dev15Aditya I can't assign it too you only PA can do that. And as I created the issue I will be assigned first

**Comment by dev15Aditya** [comment]
Cool. That's fine. I have solved the issue. Raising PR, so that you can take reference. Should I?

**Comment by aditiverma-21** [comment]
That's not the protocol. First It should be assigned then the PRs are raised. Don't spam on other's issue Please
