### ISSUE TITLE
👋 I wrote a post about Postman API Challenge 

### ISSUE THREAD

**Issue by iarmaanx** [GSSoC24/Postman-Challenge#2401]
### Here's the link to the post - https://www.linkedin.com/posts/iarmaanx_postmanchallenge-gssoc-api-activity-7255823467088945152-2R-j?utm_source=share&utm_medium=member_desktop

**Comment by iarmaanx** [comment]
My Email - thearmaandeep@gmail.com

**Comment by AKSHITHA-CHILUKA** [comment]
Great work !!
@iarmaanx

**Comment by iarmaanx** [comment]
Thanks @AKSHITHA-CHILUKA
