### ISSUE TITLE
Completed the Postman API fundamentals Student Expert Certificate 

### ISSUE THREAD

**Issue by gayu999Code** [GSSoC24/Postman-Challenge#2414]
This is like to the badge : https://api.badgr.io/public/assertions/x63ra-e5Q9GZifQWoVXViQ?identity__email=gayatri.22210039%40viit.ac.in

**Comment by Snehsk** [comment]
Congratulations @gayu999Code

**Comment by AKSHITHA-CHILUKA** [comment]
open a pr @gayu999Code
