### ISSUE TITLE
Why points is not increased after merged ?

### ISSUE THREAD

**Issue by Meetpidev** [GSSoC24/Postman-Challenge#3062]
### I added my name in add-your-certificate.md file and its accepted and merged under gssoc.. then why the points are not incresed in leaderboard ??

**Comment by Meetpidev** [comment]
@GSS0C24 Plese Review it..

**Comment by aslams2020** [comment]
Hi @Meetpidev 
Your PR has been merged 3hrs ago, Hence your points will be reflected in the next leaderboard update that is in evening.

NOTE: The leaderboard updates twice a day. firstly in morning and second in evening.
