### ISSUE TITLE
postman certification

### ISSUE THREAD

**Issue by Codersweta7** [GSSoC24/Postman-Challenge#3119]
https://api.badgr.io/public/assertions/i_jNOvQDRKqh9FF6Fa3R6w?identity__email=sweta803pandey%40gmail.com
![Screenshot_2024-11-01-14-14-37-94_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/071d3082-4585-4246-ae49-13bc8f0e5df2)

**Comment by aslams2020** [comment]
To get the points for your certification -
1. Fork the Postman repo 
2. Go to `add-your-certificate.md` file 
3. Add Your details in the same format as others which includes `name`, `linkedinlink`, `certificicate link` and `feedback` 
4. Commit the changes
5. Create a pull request.

Follow these steps @Codersweta7

**Comment by Codersweta7** [comment]
@aslams2020 
Will do it by tomorrow.

**Comment by vivekvardhan2810** [comment]
@Codersweta7  Your PR has been merged now.

You'll be able to see your points on the leaderboard in morning. Congrats! 🎉

please close this issue.
