### ISSUE TITLE
Minor Typos and Grammar Suggestions in Documentation

### ISSUE THREAD

**Issue by alienx5499** [GSSoC24/Postman-Challenge#3233]
**1. PostMan Badge Dark:**
In the section for the PostMan Badge Dark, there is a missing quotation mark before the URL. It should be:
`<img src="https://raw.githubusercontent.com/GSSoC24/Postman-Challenge/main/docs/assets/Postman%20Dark.png" width="100px" height="100px" />`

**2. Inconsistent Use of “GSSoC:**
The acronym for GirlScript Summer of Code is mentioned inconsistently throughout the document. It should consistently appear as GSSoC instead of Gssoc.

**Request:**
Please assign this issue to me and label it as documentation, typo, and suggestion.

Thank you for considering these suggestions!

**Comment by nilaygit-10721** [comment]
please assign me this issue

**Comment by Hridgit** [comment]
please assign this to me
