### ISSUE TITLE
Who are the winners of Batch 1 Postman API challenge in GSSoC'24 Extended

### ISSUE THREAD

**Issue by Abbas7120** [GSSoC24/Postman-Challenge#3402]
Who are the winners of Batch 1 Postman API challenge in GSSoC'24 Extended

_Originally posted by @Abbas7120 in https://github.com/GSSoC24/Postman-Challenge/discussions/3256#discussioncomment-11154234_

**Comment by vivekvardhan2810** [comment]
@Abbas7120 it was announced through Mail and on GSSOC official Linkedin post.

please check it.

please close this issue, if your query was resolved.
