### ISSUE TITLE
Subhadip Gayen certificate 

### ISSUE THREAD

**Issue by Subhadipgayen2006** [GSSoC24/Postman-Challenge#3650]
![Postman - Postman API Fundamentals Student Expert - 2024-11-07.png](https://github.com/user-attachments/assets/8253f265-bd9f-441a-9fba-2d090092d1a2)

**Comment by vansh-codes** [comment]
Is there a issue? Whats the purpose? please describe and specify

**Comment by vivekvardhan2810** [comment]
@Subhadipgayen2006  Your PR has been merged by the team.

You'll be able to see your points on the leaderboard in morning. Congrats! 🎉

please close this issue.

**Comment by vivekvardhan2810** [comment]
@vansh-codes please close this issue.
