### ISSUE TITLE
Add my cirtificate 

### ISSUE THREAD

**Issue by Subhadipgayen2006** [GSSoC24/Postman-Challenge#3651]
[Postman - Postman API Fundamentals Student Expert - 2024-11-07.png](https://github.com/user-attachments/assets/346e8508-8045-47d8-b678-fb8c0651cb59)
![API fundamental student expert.pdf](https://github.com/user-attachments/files/17657065/API.fundamental.student.expert.pdf)

**Comment by vivekvardhan2810** [comment]
@Subhadipgayen2006 Your PR has been merged by the team.

You'll be able to see your points on the leaderboard in morning. Congrats! 🎉

please close this issue.

**Comment by Subhadipgayen2006** [comment]
Thanks
