### ISSUE TITLE
Add my certificate

### ISSUE THREAD

**Issue by shaina123786** [GSSoC24/Postman-Challenge#3703]
https://api.badgr.io/public/assertions/cGY1k98LQGK5fB21aREERg?identity__email=nawazshaina4%40gmail.com

**Comment by vivekvardhan2810** [comment]
@shaina123786 Your PR has been merged by the team.

You'll be able to see your points on the leaderboard in morning. Congrats! 🎉

please close this issue.

**Comment by vivekvardhan2810** [comment]
@vansh-codes please close this issue.

this was resolved.
