### ISSUE TITLE
Task: Add a book

### ISSUE THREAD

**Issue by TheDinosaurLover** [GSSoC24/Postman-Challenge#3705]
I am facing error 404... can someone help me with this?
![Screenshot 2024-11-07 170439](https://github.com/user-attachments/assets/324661a2-94fa-4a04-9910-85f4b23a233d)

**Comment by vansh-codes** [comment]
Please raise your query [here](https://github.com/GSSoC24/Postman-Challenge/discussions) to get assistance related to POSTMAn certifications
