### ISSUE TITLE
Add my certificate

### ISSUE THREAD

**Issue by Anuj3553** [GSSoC24/Postman-Challenge#3768]
https://api.badgr.io/public/assertions/AyD9sdIUR1in78D9Xg5hKA?identity__email=anujverma3553%40gmail.com

**Comment by vinit105** [comment]
Task 9: Claim your points on Leaderboard:🏅
Raise the PR here: 🔗[Link to Repo](https://github.com/GSSoC24/Postman-Challenge)

Also watch this too https://gssoc24.github.io/Postman-Challenge/
