### ISSUE TITLE
Add Postman Certificate

### ISSUE THREAD

**Issue by Rx-Metallica** [GSSoC24/Postman-Challenge#3865]
https://api.badgr.io/public/assertions/hBi6oWXkR5i3sZKvM6BGPg?identity__email=adityamote478%40gmail.com

**Comment by vivekvardhan2810** [comment]
@Rx-Metallica Your PR has been merged by the team.

You'll be able to see your points on the leaderboard in evening. Congrats! 🎉

Now please close this issue.
