### ISSUE TITLE
Add postman certificate

### ISSUE THREAD

**Issue by sakshikedari** [GSSoC24/Postman-Challenge#3908]
https://badgr.com/backpack/badges/672dc764ab91e618526d2693

**Comment by BhavikaPachauri** [comment]
can i add your certificate

**Comment by BhavikaPachauri** [comment]
I add your certificate

**Comment by vivekvardhan2810** [comment]
@sakshikedari To get the points for your certification -

Fork the Postman repo

Go to add-your-certificate.md file

Add Your details in the same format as others which includes name, linkedinlink, certificicate link and feedback

Commit the changes

Create a pull request.

Follow these steps @sakshikedari 

please close this issue.

**Comment by vivekvardhan2810** [comment]
@AKSHITHA-CHILUKA this was the issue happened.

**Comment by AKSHITHA-CHILUKA** [comment]
ohh I see but it is not merged now so no worries

**Comment by vivekvardhan2810** [comment]
okay @AKSHITHA-CHILUKA, got it.

**Comment by sakshikedari** [comment]
Sir can I directly merged the changes into main main branch there is an
issue with creating a pull request
