### ISSUE TITLE
Certificate postman 

### ISSUE THREAD

**Issue by DJKILLEER** [GSSoC24/Postman-Challenge#4102]
Please can you make my certificate IN.

**Comment by vivekvardhan2810** [comment]
@DJKILLEER Your PR has been merged by the team.

You'll be able to see your points on the leaderboard in evening. Congrats! 🎉

please close this issue.

**Comment by DJKILLEER** [comment]
Thanku bhaiya 🙏lots love form Gujarat

**Comment by vivekvardhan2810** [comment]
@DJKILLEER always welcome.

and keep contributing to open source.

and please close this issue.

**Comment by DJKILLEER** [comment]
Thanks, I will.

**Comment by DJKILLEER** [comment]
Thanks for resolving team!
