### ISSUE TITLE
Posted my Postman API Certificate on Twitter with required tags

### ISSUE THREAD

**Issue by PrityanshuSingh** [GSSoC24/Postman-Challenge#4245]
Here is my tweet link : https://x.com/PrityanshuSingh/status/1855301544918315085

![Postman - Postman API Fundamentals Student Expert - 2024-10-26 (1)](https://github.com/user-attachments/assets/4acebf7d-d3c8-4373-8974-0688cacda9a2)
![Postman API Cert](https://github.com/user-attachments/assets/8a24f3c3-e1b6-4c40-8a6e-a10f85d21e5c)

**Comment by vansh-codes** [comment]
You have to fill this google form to be eligible for giveaway
https://docs.google.com/forms/d/e/1FAIpQLSeTWfWhprjNM0u842v1ieoMmFOdzraLmn7GMv_Vm_GYdMJH5g/alreadyresponded
