### ISSUE TITLE
Poor Alignment in add-your-certificate.md

### ISSUE THREAD

**Issue by SumitDwivedi24X** [GSSoC24/Postman-Challenge#465]
Description:
The add-your-certificate.md file currently has poor alignment, which makes it difficult to read and navigate. The misalignment affects the readability of the content, especially when viewing certificates, email addresses, and comments. Proper alignment is crucial for maintaining the quality and usability of the documentation.

Screenshot:
![Screenshot (302)](https://github.com/user-attachments/assets/0df4dec4-e6fa-4fcf-8fa8-a68d2b8b0e39)

**Comment by SakshamShandilya** [comment]
We will be fixing it soon!
