### ISSUE TITLE
Points not assigned

### ISSUE THREAD

**Issue by sharmi4590** [GSSoC24/Postman-Challenge#529]
Hey @sanjay-kv This morning when I saw the leaderboard 500 pts were added but after another server run on 12:50pm today my 500 pts were removed . Could you please look into it . My PR is #104 

I have postman PR in my list but not in my badges.

**Comment by sharmi4590** [comment]
![Screenshot (663)](https://github.com/user-attachments/assets/7744e4f9-6a09-4679-ab5a-7e6f6a2afbc6)
![Screenshot (664)](https://github.com/user-attachments/assets/f7dd119f-5dd6-4448-9b5e-b7c3e1158f21)
 Hey @sanjay-kv please look into it

**Comment by HarshitaSingh198** [comment]
I am also facing the same issue

**Comment by SakshamShandilya** [comment]
Kindly wait for the next leaderboard server run! It will get updated. I am keeping the issue open in case it doesn't , feel free to tag me or @sanjay-kv

**Comment by AmruthaPariprolu** [comment]
@SakshamShandilya i am facing the same issue

**Comment by Ritika128** [comment]
I am facing same issue as well

**Comment by AKSHITHA-CHILUKA** [comment]
I am facing the same issue

**Comment by sharmi4590** [comment]
@SakshamShandilya  @sanjay-kv still the leaderboard has not changed .

**Comment by Abhishek-465** [comment]
@SakshamShandilya Still the leaderboard has not changed.

**Comment by abhinov956tech-developer** [comment]
@sanjay-kv @SakshamShandilya my points still not updated after completing and merging PR (Postman-Challenge)

**Comment by HarshitaSingh198** [comment]
@SakshamShandilya   the leaderboard is still not showing the points.

**Comment by YashMall** [comment]
@SakshamShandilya Same in my case. Yesterday, it was showing 500 points and today it's showing 0. My PR is #362. Kindly see to it. Thanks.

**Comment by abhinov956tech-developer** [comment]
after the recent server run my listed PR No (2046) in the leaderboard got removed or not showing 
Kindly look into this @SakshamShandilya @sanjay-kv

**Comment by sharmi4590** [comment]
@SakshamShandilya @sanjay-kv Now even normal PRs are been removed , I made a total 32 PRs with gssoc label but in the leaderboard only 27 are visible.

**Comment by AmruthaPariprolu** [comment]
@SakshamShandilya @sanjay-kv i am facing the same issue.nearly 10-15 of my PRs are been removed

**Comment by AKSHITHA-CHILUKA** [comment]
@sanjay-kv Same issue many of my pr's have been removed

**Comment by AmruthaPariprolu** [comment]
@SakshamShandilya @sanjay-kv postman points not been assigned
kindly resolve this issue.
