### ISSUE TITLE
Points are not assigned

### ISSUE THREAD

**Issue by Satuti99** [GSSoC24/Postman-Challenge#742]
Respected sir @Princegupta101 I am able to see postman PR but my score is not updated.

![image](https://github.com/user-attachments/assets/9d2f6145-3e8e-411c-8853-fa8d50ac5f3f)

**Comment by MastanSayyad** [comment]
@Satuti99 

![image](https://github.com/user-attachments/assets/4d9e8375-c795-4789-b3d5-6f765372a2db)
