### ISSUE TITLE
Issue with Leaderboard Points and Username Visibility

### ISSUE THREAD

**Issue by biswas-12** [GSSoC24/Postman-Challenge#755]
Respected @sanjay-kv sir @Princegupta101 @SakshamShandilya sir

I noticed that my 500 points were not shown on the leaderboard yesterday after my PR was merged. Additionally, after todays GSSOC leaderboard update my name is there at serial number 219 at GSSOC Postman Challenge Page, but my GitHub username is no longer visible in GSSOC leaderboard.

Please help me out.

**Comment by MastanSayyad** [comment]
@biswas-12 Issue has been solved

![image](https://github.com/user-attachments/assets/593b5b1c-61be-469a-9fd3-2dc32792fda3)
