### ISSUE TITLE
postman points not added 

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [GSSoC24/Postman-Challenge#765]
my pr is merged but also I am unable to see my points on leaderboard

**Comment by AKSHITHA-CHILUKA** [comment]
@sanjay-kv please look into it

**Comment by MastanSayyad** [comment]
Hey @AKSHITHA-CHILUKA It has been solved yesterday itself

![image](https://github.com/user-attachments/assets/7ae0dc86-199c-412e-b79d-92ccbf4bcee8)
