### ISSUE TITLE
Getting Error in Variable in Postman

### ISSUE THREAD

**Issue by kashvi7440** [GSSoC24/Postman-Challenge#774]
GET http://library-api.postmanlabs.com/books
Error: connect ECONNREFUSED 107.23.125.113:80
Network
Request Headers
User-Agent: PostmanRuntime/7.40.0
Accept: */*
Cache-Control: no-cache
Postman-Token: 9f094032-9c24-4e2c-a1cc-bad8d7ba5051
Host: 

Accept-Encoding: gzip, deflate, br
Connection: keep-alive

After creating , i click on the send button then the above message appeared.What should i do now?

**Comment by MastanSayyad** [comment]
@kashvi7440 I think we have discussed it in one of your discussions, let me know further there!
