### ISSUE TITLE
Suggested Improvements in Readme File

### ISSUE THREAD

**Issue by Vin205** [GSSoC24/Postman-Challenge#840]
Add Table of Contents: A table of contents at the beginning helps users quickly navigate through the document.
Explain Customization: Provide more detailed explanations of how users can customize the badges, including changing width, height, and gap values
![IMG_20240730_163004](https://github.com/user-attachments/assets/cdabeb6d-ae26-436a-a97e-91b721ddcced)
![IMG_20240730_163029](https://github.com/user-attachments/assets/f45524a1-a44e-4b94-904d-a2014a118674)

**Comment by SakshamShandilya** [comment]
Sure , thank you fo your feedback ! The team will surely look into it
