### ISSUE TITLE
pull request cannot be merge (always show conflict)

### ISSUE THREAD

**Issue by Akash-nema** [GSSoC24/Postman-Challenge#904]
I resolve all conflicts and then again commit but every time shows conflict again  please help @sanjay-kv  me how to resolve conflict  properly (I watched a full video on how to pull and commit a request  which is mentioned in a guided sheet of Postman API)

**Comment by Akash-nema** [comment]
my PR no. is #853

**Comment by Hemu21** [comment]
@Akash-nema  your pr is merged so closing this issue.
