### ISSUE TITLE
Points are not awarded in the leaderboard 

### ISSUE THREAD

**Issue by Praneeth-2602** [GSSoC24/Postman-Challenge#964]
The points for completing this challenge were not awarded...

**Comment by MastanSayyad** [comment]
Hey @Praneeth-2602 Your points will get added in the next leaderboard update (till the evening) as your PR got merged recently!

**Comment by Praneeth-2602** [comment]
Ok sir, I was worried because today is the last day

**Comment by MastanSayyad** [comment]
Hey @Praneeth-2602 today is not the last day, gssoc has been extended till 10th Aug 2024
